### ISSUE TITLE
pointfree.io is down

### ISSUE THREAD

**Issue by noughtmare** [keathley/pointfree.io#19]
Probably due to Heroku ending the free plans.

Someone on reddit suggested switching to https://fly.io

See: https://reddit.com/r/haskell/comments/z9eyu7/monthly_hask_anything_december_2022/iyhfk30/

**Comment by keathley** [comment]
Yup. Its Heroku issues. I'm happy to move it to fly but I haven't had time to sit down and get a working docker container for the app. If someone would like to submit a PR with that, I'll get it pushed up.

**Comment by stackptr** [comment]
pointfree.io appears to be online now.
