### ISSUE TITLE
Tuple to z returns id

### ISSUE THREAD

**Issue by jorisburgers** [keathley/pointfree.io#9]
The expression `\(_,_) -> z` return `id`, which is not correct. It works only with the `z` on the right hand side, `a` on the right produces the valid `const a`.

**Comment by keathley** [comment]
z is a special character in haskell as described here: https://ghc.haskell.org/trac/ghc/wiki/Commentary/Compiler/SymbolNames#AlphanumericCharacters. That is why you are seeing those results. If you escape the character z you will get the correct results.
